import type { Tenant } from "@/lib/types"

export const tenants: Tenant[] = [
  {
    id: "t1",
    slug: "acme-retail",
    name: "Acme Retail",
    logoInitial: "A",
    logoColor: "bg-blue-600",
    plan: "enterprise",
    status: "active",
    ownerName: "Sarah Johnson",
    ownerEmail: "sarah@acmeretail.com",
    usersCount: 24,
    storesCount: 5,
    mrr: 499,
    createdAt: "2024-01-12",
    country: "United States",
  },
  {
    id: "t2",
    slug: "urban-mart",
    name: "Urban Mart",
    logoInitial: "U",
    logoColor: "bg-violet-600",
    plan: "growth",
    status: "active",
    ownerName: "Daniel Kim",
    ownerEmail: "daniel@urbanmart.io",
    usersCount: 11,
    storesCount: 2,
    mrr: 199,
    createdAt: "2024-03-04",
    country: "Canada",
  },
  {
    id: "t3",
    slug: "fresh-grocer",
    name: "Fresh Grocer",
    logoInitial: "F",
    logoColor: "bg-emerald-600",
    plan: "starter",
    status: "trial",
    ownerName: "Amelia Clarke",
    ownerEmail: "amelia@freshgrocer.com",
    usersCount: 3,
    storesCount: 1,
    mrr: 0,
    createdAt: "2026-07-20",
    trialEndsAt: "2026-08-10",
    country: "United Kingdom",
  },
  {
    id: "t4",
    slug: "north-hardware",
    name: "North Hardware Co.",
    logoInitial: "N",
    logoColor: "bg-orange-600",
    plan: "growth",
    status: "active",
    ownerName: "Marcus Lee",
    ownerEmail: "marcus@northhardware.com",
    usersCount: 8,
    storesCount: 3,
    mrr: 199,
    createdAt: "2023-11-28",
    country: "Australia",
  },
  {
    id: "t5",
    slug: "bella-boutique",
    name: "Bella Boutique",
    logoInitial: "B",
    logoColor: "bg-pink-600",
    plan: "starter",
    status: "suspended",
    ownerName: "Isabella Rossi",
    ownerEmail: "isabella@bellaboutique.it",
    usersCount: 2,
    storesCount: 1,
    mrr: 49,
    createdAt: "2024-06-15",
    country: "Italy",
  },
  {
    id: "t6",
    slug: "techstop",
    name: "TechStop Electronics",
    logoInitial: "T",
    logoColor: "bg-cyan-600",
    plan: "enterprise",
    status: "active",
    ownerName: "Priya Patel",
    ownerEmail: "priya@techstop.com",
    usersCount: 32,
    storesCount: 7,
    mrr: 499,
    createdAt: "2023-08-02",
    country: "India",
  },
]

export function getTenantBySlug(slug: string): Tenant | undefined {
  return tenants.find((t) => t.slug === slug)
}
