CREATE TABLE "store_roles" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
	"store_id" uuid NOT NULL,
	"name" text NOT NULL,
	"description" text,
	"is_system" boolean DEFAULT false NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "store_role_permissions" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
	"role_id" uuid NOT NULL,
	"can_view_dashboard" boolean DEFAULT false NOT NULL,
	"can_use_pos" boolean DEFAULT false NOT NULL,
	"can_view_branches" boolean DEFAULT false NOT NULL,
	"can_create_branches" boolean DEFAULT false NOT NULL,
	"can_edit_branches" boolean DEFAULT false NOT NULL,
	"can_delete_branches" boolean DEFAULT false NOT NULL,
	"can_view_members" boolean DEFAULT false NOT NULL,
	"can_invite_members" boolean DEFAULT false NOT NULL,
	"can_edit_members" boolean DEFAULT false NOT NULL,
	"can_delete_members" boolean DEFAULT false NOT NULL,
	"can_view_products" boolean DEFAULT false NOT NULL,
	"can_create_products" boolean DEFAULT false NOT NULL,
	"can_edit_products" boolean DEFAULT false NOT NULL,
	"can_delete_products" boolean DEFAULT false NOT NULL,
	"can_view_categories" boolean DEFAULT false NOT NULL,
	"can_create_categories" boolean DEFAULT false NOT NULL,
	"can_edit_categories" boolean DEFAULT false NOT NULL,
	"can_delete_categories" boolean DEFAULT false NOT NULL,
	"can_view_sub_categories" boolean DEFAULT false NOT NULL,
	"can_create_sub_categories" boolean DEFAULT false NOT NULL,
	"can_edit_sub_categories" boolean DEFAULT false NOT NULL,
	"can_delete_sub_categories" boolean DEFAULT false NOT NULL,
	"can_view_brands" boolean DEFAULT false NOT NULL,
	"can_create_brands" boolean DEFAULT false NOT NULL,
	"can_edit_brands" boolean DEFAULT false NOT NULL,
	"can_delete_brands" boolean DEFAULT false NOT NULL,
	"can_view_units" boolean DEFAULT false NOT NULL,
	"can_create_units" boolean DEFAULT false NOT NULL,
	"can_edit_units" boolean DEFAULT false NOT NULL,
	"can_delete_units" boolean DEFAULT false NOT NULL,
	"can_view_variant_attributes" boolean DEFAULT false NOT NULL,
	"can_create_variant_attributes" boolean DEFAULT false NOT NULL,
	"can_edit_variant_attributes" boolean DEFAULT false NOT NULL,
	"can_delete_variant_attributes" boolean DEFAULT false NOT NULL,
	"can_view_warranties" boolean DEFAULT false NOT NULL,
	"can_create_warranties" boolean DEFAULT false NOT NULL,
	"can_edit_warranties" boolean DEFAULT false NOT NULL,
	"can_delete_warranties" boolean DEFAULT false NOT NULL,
	"can_view_expired_products" boolean DEFAULT false NOT NULL,
	"can_view_low_stocks" boolean DEFAULT false NOT NULL,
	"can_manage_stock" boolean DEFAULT false NOT NULL,
	"can_adjust_stock" boolean DEFAULT false NOT NULL,
	"can_transfer_stock" boolean DEFAULT false NOT NULL,
	"can_print_barcode" boolean DEFAULT false NOT NULL,
	"can_print_qr_code" boolean DEFAULT false NOT NULL,
	"can_view_customers" boolean DEFAULT false NOT NULL,
	"can_create_customers" boolean DEFAULT false NOT NULL,
	"can_edit_customers" boolean DEFAULT false NOT NULL,
	"can_delete_customers" boolean DEFAULT false NOT NULL,
	"can_view_suppliers" boolean DEFAULT false NOT NULL,
	"can_create_suppliers" boolean DEFAULT false NOT NULL,
	"can_edit_suppliers" boolean DEFAULT false NOT NULL,
	"can_delete_suppliers" boolean DEFAULT false NOT NULL,
	"can_view_warehouses" boolean DEFAULT false NOT NULL,
	"can_create_warehouses" boolean DEFAULT false NOT NULL,
	"can_edit_warehouses" boolean DEFAULT false NOT NULL,
	"can_delete_warehouses" boolean DEFAULT false NOT NULL,
	"can_view_sales_report" boolean DEFAULT false NOT NULL,
	"can_view_purchase_report" boolean DEFAULT false NOT NULL,
	"can_view_inventory_report" boolean DEFAULT false NOT NULL,
	"can_view_invoice_report" boolean DEFAULT false NOT NULL,
	"can_view_customer_report" boolean DEFAULT false NOT NULL,
	"can_view_supplier_report" boolean DEFAULT false NOT NULL,
	"can_view_product_report" boolean DEFAULT false NOT NULL,
	"can_manage_settings" boolean DEFAULT false NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE UNIQUE INDEX "store_role_name_unique" ON "store_roles" ("store_id","name");--> statement-breakpoint
CREATE INDEX "store_role_store_idx" ON "store_roles" ("store_id");--> statement-breakpoint
CREATE INDEX "store_role_system_idx" ON "store_roles" ("is_system");--> statement-breakpoint
CREATE UNIQUE INDEX "store_role_permission_role_unique" ON "store_role_permissions" ("role_id");--> statement-breakpoint
CREATE INDEX "store_role_permission_role_idx" ON "store_role_permissions" ("role_id");--> statement-breakpoint
ALTER TABLE "store_roles" ADD CONSTRAINT "store_roles_store_id_store_id_fkey" FOREIGN KEY ("store_id") REFERENCES "store"("id") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "store_role_permissions" ADD CONSTRAINT "store_role_permissions_role_id_store_roles_id_fkey" FOREIGN KEY ("role_id") REFERENCES "store_roles"("id") ON DELETE CASCADE;